border:
 radius: 250
 center:
   x: 0
   y: 0
 shrink:
  amount: 1
  interval: 60
  limit: 10

air_drop:
 drop_time: 30
 interval: 60

podium:
 first:
  x: 0
  y: 0
  z: 0
 second:
  x: 0
  y: 0
  z: 0
 third:
  x: 0
  y: 0
  z: 0
 area:
  1:
   x: 0
   y: 0
  2:
   x: 0
   y: 0