# Event FFA Configuration

# Podium coordinates for teleportation after FFA ends
podium:
  first:
    world: "world"
    x: 0.0
    y: 100.0
    z: 10.0
  second:
    world: "world"
    x: 5.0
    y: 100.0
    z: 10.0
  third:
    world: "world"
    x: -5.0
    y: 100.0
    z: 10.0
  other:
    world: "world"
    x: 0.0
    y: 100.0
    z: 0.0

# Border settings
border:
  center_x: 0.0  # X coordinate for border center
  center_z: 0.0  # Z coordinate for border center
  radius: 1000   # Initial border radius in blocks
  shrink_per_time: 50  # blocks to shrink every interval
  shrink_interval: 300  # seconds between shrinks

# Air drop settings
air_drop:
  drop_time: 30   # seconds after announcement before drop lands
  interval: 180   # seconds between air drop spawns

# Sounds
sounds:
  kill: "ENTITY_PLAYER_LEVELUP"  # sound played globally on kills